//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miniblog.Core.Texts.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miniblog.Core.Texts.Home.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre mi.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen de los hechos relevantes tanto de mi trayectoria profesional, como de mi formación académica..
        /// </summary>
        public static string BioDescription {
            get {
                return ResourceManager.GetString("BioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biografía.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Blog personal sobre desarrollo y aplicaciones. Contiene una recopilación de artículos que he escrito en estos años de aprendizaje de nuevas tecnologías, y otros escritos dentro de mi actividad profesional..
        /// </summary>
        public static string BlogDescription {
            get {
                return ResourceManager.GetString("BlogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conecta conmigo.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web personal de Sergi Gisbert. Listado de proyectos y biografía personal. Datos de contacto.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimos tweets.
        /// </summary>
        public static string LastTweets {
            get {
                return ResourceManager.GetString("LastTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Sitecore 9.1 Certified developer.
        /// </summary>
        public static string Lead1 {
            get {
                return ResourceManager.GetString("Lead1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especializado en el desarrollo de aplicaciones web corporativas mediante CMS: Sitecore, Kentico &amp; Umbraco. Últimamente, responsable del desarrollo de diferentes proyectos de Sitecore con SXA framework y sincronización con MS Dynamics CRM.
        ///DevOps Engineer, configuración de entornos CI/CD con Azure DevOps Build &amp; Release pipelines..
        /// </summary>
        public static string Lead2 {
            get {
                return ResourceManager.GetString("Lead2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualmente, Sitecore Architect en .
        /// </summary>
        public static string Lead3 {
            get {
                return ResourceManager.GetString("Lead3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyectos.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recopilación tanto de proyectos en los que he trabajado durante mi trayectoria profesional, como proyectos propios y de código abierto..
        /// </summary>
        public static string ProjectsDescription {
            get {
                return ResourceManager.GetString("ProjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los derechos reservados..
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Architecht &amp; Developer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
