
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#region " Espacios de nombres "

using System.IO;
using System.Runtime.Serialization;
using Common.Utils.Strings;
using DataAnnotations.Utils;
using DTO.Projects;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

#endregion

namespace DTO.Projects
{
	/// Generated at 16/12/2013
	[Serializable]
	[DataContract(Name = "DtoImage", Namespace = "DTO.Projects")]
	public partial class DtoImage : DtoBase, IDtoImage
	{
		#region " Atributos "

		/// <summary>
		/// Nombre de la imagen
		/// </summary>
		private String name;

		/// <summary>
		/// ULR de la imagen
		/// </summary>
		private String url;

		/// <summary>
		/// Para prevenir disposiciones sucesivas
		/// </summary>
		private bool disposed; 
		
		#endregion
	
		#region " Propiedades "
		
		/// <summary>
		/// Obtiene o establece "Nombre de la imagen"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "Nombre de la imagen"</value>
		[RequiredLocalized]
		[StringLengthLocalized(50)]
		[DataMember]
		public String Name
		{
			get { return name; }
			set { name = value; }
		}
		
		/// <summary>
		/// Obtiene o establece "ULR de la imagen"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "ULR de la imagen"</value>
		[RequiredLocalized]
		[StringLengthLocalized(250)]
		[DataMember]
		public String Url
		{
			get { return url; }
			set { url = value; }
		}
		
		#endregion
	
		#region " Constructores "
		
		/// <summary>
	    /// Inicializa una nueva instancia de la class <see cref="DtoImage"/>.
	    /// </summary>
		public DtoImage() { }
	
	    /// <summary>
	    /// Inicializa una nueva instancia de la class <see cref="DtoImage"/>.
	    /// </summary>
	    /// <param name="instantiatedObject">Si es <c>true</c> instancia los objetos que formen parte de esta clase.</param>
		public DtoImage(Boolean instantiatedObject=false)
		{
			if (!instantiatedObject) return;
		}
	
		/// <summary>
	    /// Finaliza una instancia de la class <see cref="DtoImage"/> y libera sus recursos.
	    /// </summary>
		~DtoImage() 
	    {
	        Dispose(false);
	    }
	
	    /// <summary>
	    /// Libera el espacio reservado por sus objetos.
	    /// </summary>
		protected override void Dispose(bool disposing)
		{
			if (!disposed)
			{
				disposed = true;
			}
		}
	
		#endregion
	
		#region " Sobrecargas "

		/// <summary>
		/// Sobrecarga del método ToString() para la this.Element DtoImage
		/// </summary>
		/// <returns>Un <see cref="System.String"/> que representa este DtoImage</returns>
		public override String ToString()
		{
			return (String.IsNullOrEmpty(name) ? "" : name);
		}
		
		/// <summary>
		/// Delegado que se utiliza para ordenar las listas tipadas.
		/// </summary>
		/// <param name="x">Primer elemento a comparar</param>
		/// <param name="y">Segundo elemento a comparar</param>
		/// <returns>-1: y es mayor que x; 0: son iguales; 1: x es mayor que y</returns>
		public static int Compare(object x, object y)
		{
			if (x == null) return (y == null) ? 0 : -1;
			if (y == null) return 1;
			if (x.GetType() != typeof(DtoImage)) return -1;
			if (y.GetType() != typeof(DtoImage)) return 1;
		
			return ((DtoImage)x).CompareTo(y);
		}
		
		/// <summary>
		/// Compara la instancia con el objeto recibe por parámetro.
		/// </summary>
		/// <param name="obj">Objeto con el que se compara la instancia.</param>
		/// <returns>-1: el parámetro es mayor que la instancia; 0: son iguales; 1: la instancia es mayor que el parámetro</returns>
		public override int CompareTo(object obj)
		{
			if ((obj == null) || ((obj.GetType() != typeof(DtoImage)))) return 1;
			
			DtoImage dtoImage = (DtoImage)obj;
			if (Id != dtoImage.Id)
				return (Id < dtoImage.Id) ? -1 : 1;
			if (!String.Equals(Name, dtoImage.Name, StringComparison.CurrentCultureIgnoreCase))
				return (String.Compare(Name, dtoImage.Name, StringComparison.CurrentCultureIgnoreCase));
			
			return 0;
		}
		
		/// <summary>
		/// Compara la instancia con el objeto recibe por parámetro.
		/// </summary>
		/// <param name="obj">Objeto con el que se compara la instancia.</param>
		/// <returns>True son iguales los objeto, false tienen algún campo distinto</returns>
		public override Boolean Equals(object obj)
		{
			if ((obj == null) || ((obj.GetType() != typeof (DtoImage)))) return false;
		
			DtoImage image = (DtoImage)obj;
			return Equals(this, image);
		}
		
		/// <summary>
		/// Compara si las dos instancias son iguales.
		/// </summary>
		/// <param name="x">Primera instancia a comparar.</param>
		/// <param name="y">Segunda instancia a comparar.</param>
		/// <returns>Determina si las dos instancias tienen todos los campos iguales.</returns>
		public static new Boolean Equals(object x, object y)
		{
			if ((x == null) && (y == null)) return true;
			if ((x == null) || (y == null)) return false;
		
			if (x.GetType() != typeof(DtoImage)) return false;
			if (y.GetType() != typeof(DtoImage)) return false;
		
			DtoImage image1 = (DtoImage)x;
			DtoImage image2 = (DtoImage)y;
			if (image1.Id != image2.Id) return false;		
			if (!String.Equals(image1.Name, image2.Name, StringComparison.CurrentCultureIgnoreCase)) return false;
			return true;
		}
		
		#endregion
	}
}
