//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#region " Espacios de nombres "

using Common.Utils.Strings;
using DTO.Projects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using DataAnnotations.Utils;

#endregion

namespace DTO.Projects
{
	/// Generated at 17/12/2013
	public interface IDtoProject : IDto
	{
		#region " Propiedades "
	
		/// <summary>
		/// Obtiene o establece "Nombre del proyecto"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "Nombre del proyecto"</value>
		String Name { get; set; }
		
		/// <summary>
		/// Obtiene o establece "Descripción del proyecto"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "Descripción del proyecto"</value>
		String Description { get; set; }
		
		/// <summary>
		/// Obtiene o establece "URL del proyecto"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "URL del proyecto"</value>
		String Url { get; set; }
		
		/// <summary>
		/// Obtiene o establece "Fechas del proyecto"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "Fechas del proyecto"</value>
		String Date { get; set; }
		
		/// <summary>
		/// Obtiene o establece "Slug del proyecto"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "Slug del proyecto"</value>
		String Slug { get; set; }
		
		/// <summary>
		/// Obtiene o establece "Listado de tecnologías del proyecto"
		/// </summary>
		/// <value><see cref="List<String>"/>Obtiene o establece "Listado de tecnologías del proyecto"</value>
		List<String> Technologies { get; set; }
		
		/// <summary>
		/// Obtiene o establece "Tareas desarrolladas en el proyecto"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "Tareas desarrolladas en el proyecto"</value>
		String Tasks { get; set; }
		
		/// <summary>
		/// Obtiene o establece "Descripción extendida del proyecto"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "Descripción extendida del proyecto"</value>
		String FullDescription { get; set; }
		
		#endregion
		
	}
}
