//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#region " Espacios de nombres "

using Common.Utils.Strings;
using DTO.Projects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using DataAnnotations.Utils;

#endregion

namespace DTO.Projects
{
	/// Generated at 16/12/2013
	public interface IDtoBusiness : IDto
	{
		#region " Propiedades "
	
		/// <summary>
		/// Obtiene o establece "Nombre de la empresa"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "Nombre de la empresa"</value>
		String Name { get; set; }
		
		/// <summary>
		/// Obtiene o establece "URL de la empresa"
		/// </summary>
		/// <value><see cref="String"/>Obtiene o establece "URL de la empresa"</value>
		String Url { get; set; }
		
		#endregion
		
	}
}
