//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miniblog.Core.Texts.Bio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miniblog.Core.Texts.Bio.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formación académica.
        /// </summary>
        public static string Academic {
            get {
                return ResourceManager.GetString("Academic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máster en desarrollo de aplicaciones y servicios web.
        /// </summary>
        public static string Academic1 {
            get {
                return ResourceManager.GetString("Academic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre, 2007 - Junio, 2008.
        /// </summary>
        public static string Academic1Dates {
            get {
                return ResourceManager.GetString("Academic1Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingeniero en Informática.
        /// </summary>
        public static string Academic2 {
            get {
                return ResourceManager.GetString("Academic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre, 1995 - Junio, 2001.
        /// </summary>
        public static string Academic2Dates {
            get {
                return ResourceManager.GetString("Academic2Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior .Net Developer.
        /// </summary>
        public static string CPTitle {
            get {
                return ResourceManager.GetString("CPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web personal de Sergi Gisbert. Biografía personal. Experiencia laboral y formación académica..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Technology Officer - CTO.
        /// </summary>
        public static string EstratoTitle {
            get {
                return ResourceManager.GetString("EstratoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiencia profesional.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracto general.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore Architect .
        /// </summary>
        public static string KabelTitle {
            get {
                return ResourceManager.GetString("KabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitecore Architect.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecnologías principales.
        /// </summary>
        public static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biografía.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable de Programación. Analista.
        /// </summary>
        public static string Virtua2Title {
            get {
                return ResourceManager.GetString("Virtua2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director técnico en Virtua.
        /// </summary>
        public static string VirtuaTitle {
            get {
                return ResourceManager.GetString("VirtuaTitle", resourceCulture);
            }
        }
    }
}
